name: GitHub Actions Demo

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Branch-Specific Commands
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "Running commands for the main branch"
            # Your main branch-specific command here
          elif [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            echo "Running commands for the dev branch"
            # Your dev branch-specific command here
          else
            echo "No commands defined for this branch."
          fi
